version: "3.9"
name: "dynamic-user-segmentation"

services:
  postgres:
    image: postgres:15
    user: "postgres"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: "dynamic-user-segmentation_db"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "dynamic-user-segmentation_db" ]
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      dynamic-user-segmentation:

  migration:
    build:
      context: ../.
      dockerfile: ./deployments/migration/Dockerfile
    environment:
      DATABASE_URL: "postgres://postgres:1234@postgres:5432/dynamic-user-segmentation_db?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      dynamic-user-segmentation:

  service:
    build:
      context: ../.
      dockerfile: ./deployments/dynamic-user-segmentation/Dockerfile
    env_file:
      - ../configs/dynamic-user-segmentation.env
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_started
    ports:
      - '8080:8080'
    networks:
      dynamic-user-segmentation:

networks:
  dynamic-user-segmentation:
    name: "dynamic-user-segmentation_network"

volumes:
  pgdata: