zap_logger:
  level: "info"
  encoding: "json"
  output_path: ["stdout"]
  error_output_path: ["stdout"]

postgres_storage:
  host: "postgres"
  port: "5432"
  db_name: "dynamic-user-segmentation_db"
  sslmode: "disable"
  max_conns: 5
  min_conns: 3
  max_conn_lifetime: "1h"
  max_conn_idle_time: "1m"