zap_logger:
  level:
  encoding:
  output_path:
  error_output_path:

postgres_storage:
  host:
  port:
  db_name:
  sslmode:
  max_conns:
  min_conns:
  max_conn_lifetime:
  max_conn_idle_time:

server:
  host:
  port:
  read_timeout:
  write_timeout:

auto_add_ticker:
path_to_reports: